sweep:
  description: "Demo sweep"
  project: ethiopia-sweep
  name: demo
  method: bayes  # grid or "random" or "bayes"
  metric:
    name: meta_score
    goal: minimize

  parameters:
    encoder:
      parameters:
        enable_decomposed_continuous:
          values: [True, False]

    model:
      parameters:
        latent_size_2:
          distribution: int_uniform
          min: 0
          max: 6
        beta:
          distribution: log_uniform_values
          min: 0.0001
          max: 1
        lr:
          distribution: log_uniform_values
          min: 0.0001
          max: 0.1
        dropout:
          min: 0
          max: 0.5
        skips:
          values: [True, False]
        normalize:
          values: [True, False]
        hidden_size_2:
          min: 3
          max: 10
        sampler:
          values: [argmax, multinomial]

        controls_encoder:
          parameters:
            depth:
              min: 1
              max: 4

        encoder:
          parameters:
            depth:
              min: 1
              max: 4

        decoder:
          parameters:
            depth:
              min: 1
              max: 4

seed: 12345

logging:
  dir: "logs"

data:
  train_path: data/ethiopia/ethiopia_data_cleaned.csv
  columns: [
        age,
        sex,
        dist_road,
        dist_market,
        dist_border,
        dist_popcenter,
        dist_admhq,
        denomination,
        total_cons_ann,
        nom_totcons_aeq,
        walls_material,
        roof_material,
        floor_material,
  ]
  controls: [
    sex,
    age,
    denomination,
  ]

encoder:
  enable_decomposed_continuous: False
  max_components: 10
  learn_rounding_scheme: False
  enforce_min_max_values: True

datamodule:
  val_split: 0.1
  test_split: 0.0
  train_batch_size: 1024
  val_batch_size: 1024
  test_batch_size: 1024
  gen_batch_size: 1024
  num_workers: 4
  pin_memory: False

gen_dataloader:
  batch_size: 1024
  num_workers: 4
  pin_memory: False

model:
  latent_size_2: 5
  beta: 0.1
  lr: 0.0001
  dropout: 0.3
  activation: True
  normalize: True
  controls_encoder:
    depth: 3
  encoder:
    depth: 2
  decoder:
    depth: 2
  sampler: argmax

early_stopping:
  patience: 20

trainer:
  min_epochs: 10
  max_epochs: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 10

generate:
  target_path: None

evaluate:
  orders: [1,2,3]
  homogeneity: True
  incorrectness: True