seed: 12345

logging:
  dir: "logs"
  project: "uk_census"

data:
  train_path: tmp/census.csv
  columns: {
    approx_social_grade: social,
    country_of_birth_3a: country_of_birth,
    economic_activity_status_10m: employment_status,
    ethnic_group_tb_6a: ethnicity,
    health_in_general: health,
    hh_families_type_6a: household_type,
    hours_per_week_worked: hours_worked,
    in_full_time_education: full_time_student,
    industry_10a: industry,
    iol22cd: io_london,
    legal_partnership_status_6a: marital_status,
    occupation_10a: occupation,
    region: region,
    religion_tb: religion,
    residence_type: residence_type,
    resident_age_7d: age_group,
    sex: sex,
    usual_short_student: residency_type,
  }
  controls: [
    sex,
    age_group,
    region,
  ]

encoder:
  continuous_encoding: decomposed
  max_components: 10
  learn_rounding_scheme: False
  enforce_min_max_values: False

datamodule:
  val_split: 0.1
  test_split: 0.0
  train_batch_size: 1024
  val_batch_size: 1024
  test_batch_size: 1024
  gen_batch_size: 1024
  num_workers: 4
  pin_memory: False

gen_dataloader:
  batch_size: 1024
  num_workers: 4
  pin_memory: False

model:
  latent_size_2: 5
  hidden_size_2: 8
  beta: 0.0003
  lr: 0.0001
  dropout: 0.2
  skips: True
  normalize: False
  sampler: multinomial
  use_token_weights: False
  use_weighted_controls: False
  controls_encoder:
    depth: 1
  encoder:
    depth: 3
  decoder:
    depth: 3


early_stopping:
  patience: 20

trainer:
  min_epochs: 20
  max_epochs: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 10

generate:
  target_path: None

evaluate:
  densities: [1,2,3]
  homogeneity: True
  incorrectness: True
