# free census download from publicmicrodatateachingsampleenglandandwalescensus2021
rename = {
    "resident_id_m": "pid",
    "approx_social_grade": "social",
    "country_of_birth_3a": "country_of_birth",
    "economic_activity_status_10m": "employment_status",
    "ethnic_group_tb_6a": "ethnicity",
    "health_in_general": "health",
    "hh_families_type_6a": "household_type",
    "hours_per_week_worked": "hours_worked",
    "in_full_time_education": "full_time_student",
    "industry_10a": "industry",
    "iol22cd": "inner/outer_london",
    "legal_partnership_status_6a": "marital_status",
    "occupation_10a": "occupaion",
    "region": "region",
    "religion_tb": "religion",
    "residence_type": "residence_type",
    "resident_age_7d": "age_group",
    "sex": "sex",
    "usual_short_student": "residency_type",
}

# from https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/microdatasamplecodescensus2021
lookup = {
    "approx_social_grade": {
        -8: "NA",
        1: "manager",
        2: "supervisor",
        3: "skilled",
        4: "semi-skiled",
    },
    "country_of_birth_3a": {-8: "NA", 1: "UK", 2: "non_UK"},
    "economic_activity_status_10m": {
        -8: "NA",
        1: "employee",
        2: "self_employed",
        3: "job_seeker",
        4: "employed_student",
        5: "retired",
        6: "student",
        7: "carer",
        8: "disabled",
        9: "other",
    },
    "ethnic_group_tb_6a": {
        -8: "NA",
        1: "asian",
        2: "black",
        3: "mixed",
        4: "white",
        5: "other",
    },
    "health_in_general": {
        -8: "NA",
        1: "very_good",
        2: "good",
        3: "fair",
        4: "bad",
        5: "very_bad",
    },
    "hh_families_type_6a": {
        -8: "NA",
        1: "one_person",
        2: "married_civil",
        3: "cohabiting",
        4: "lone_parent",
        5: "multi_person",
    },
    "hours_per_week_worked": {
        -8: "NA",
        1: "<15hrs/week",
        2: "16to30hrs/week",
        3: "3to48hrs/week",
        4: "49+hrs/week",
    },
    "in_full_time_education": {-8: "NA", 1: "true", 2: "false"},
    "industry_10a": {
        -8: "NA",
        1: "agriculture",
        2: "manufacturing",
        3: "energy/water",
        4: "construction",
        5: "distribution/hotesls/restaurants",
        6: "transport/communication",
        7: "finance/real_estate/professional_and_admin",
        8: "public_admin/education/health",
        9: "other",
    },
    "iol22cd": {"-8": "NA", "E13000001": "inner", "E13000002": "outer"},
    "legal_partnership_status_6a": {
        -8: "NA",
        1: "never",
        2: "married/partnership",
        3: "separated",
        4: "divorsed/disolved",
        5: "widowed",
    },
    "occupation_10a": {
        -8: "NA",
        1: "manager/director/senior",
        2: "professional",
        3: "associate_professional/technical",
        4: "admin/secretarial",
        5: "skilled_trade",
        6: "care/leisure/services",
        7: "sales/customer_service",
        8: "operator",
        9: "elementary",
    },
    "region": {
        "E12000001": "north_east",
        "E12000002": "north_west",
        "E12000003": "yorkshire/humber",
        "E12000004": "east_midlands",
        "E12000005": "west_midlands",
        "E12000006": "east_of_england",
        "E12000007": "london",
        "E12000008": "south_east",
        "E12000009": "south_west",
        "N99999999": "NI",
        "S99999999": "scotland",
        "W92000004": "wales",
    },
    "religion_tb": {
        -8: "NA",
        1: "none",
        2: "christian",
        3: "buddhist",
        4: "hindu",
        5: "jewish",
        6: "muslim",
        7: "sikh",
        8: "other",
        9: "withheld",
    },
    "residence_type": {1: "household", 2: "communal"},
    "resident_age_7d": {
        -8: "NA",
        1: "0-15",
        2: "16-24",
        3: "25-34",
        4: "35-44",
        5: "45-54",
        6: "55-64",
        7: "65+",
    },
    "sex": {-8: "NA", 1: "female", 2: "male"},
    "usual_short_student": {
        -8: "NA",
        1: "resident",
        2: "student",
        3: "short-term",
    },
}
